version: '3.8'

services:
  narendar-website:
    build: .
    container_name: narendar-website
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - narendar-network

networks:
  narendar-network:
    driver: bridge